name: PluginMinecraft1.21.3
version: '1.0-SNAPSHOT'
main: org.minecraft.pluginMinecraft1213
api-version: '1.21'
commands:
  setNewWarp:
    description: Imposta un nuovo warp.
    usage: /setNewWarp <nomeWarp>
  warp:
    description: Teletrasportati a un warp esistente.
    usage: /warp <nomeWarp>
  warpList:
    description: Ritorna la lista di warp disponibili.
    usage: /warpList
  delWarp:
    description: Cancella un warp.
    usage: /delWarp <nomeWarp>
  giveWarpBook:
    description: Givva il libro dei warp disponibili.
    usage: /giveWarpBook
  giveArmorStand:
    description: Givva un armor stand vuoto con braccia.
    usage: /giveArmorStand
  gethead:
    description: Givva la testa del player.
    usage: /gethead [nomeGiocatore]
